# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBuy():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_buy(self):
    self.driver.get("https://demowebshop.tricentis.com/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "Email").click()
    self.driver.find_element(By.ID, "Email").send_keys("miwoacc@gmail.com")
    self.driver.find_element(By.ID, "Password").send_keys("Asuraloh581321!")
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".item-box:nth-child(4) img").click()
    self.driver.execute_script("window.scrollTo(0,364)")
    self.driver.find_element(By.CSS_SELECTOR, ".product-essential").click()
    self.driver.find_element(By.ID, "addtocart_72_EnteredQuantity").send_keys("2")
    self.driver.find_element(By.ID, "add-to-cart-button-72").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
  
